### ISSUE TITLE
grunt 설치 시 node.js 설치를 해야하는데 os에 따른 버전 제한은 없습니까?

### ISSUE THREAD

**Issue by skypentum** [demun/FrontEndStudy#1]
grunt 설치 시 node.js 설치를 해야하는데 os에 따른 버전 제한은 없습니까?

**Comment by demun** [comment]
os 버젼은 상관없는데....32비트, 64비트에 대한 이슈는 있습니다.
64비트를 사용하다보면 충돌이 나곤 합니다. 
64비트라도 32비트 설치를 권장합니다.
