### ISSUE TITLE
Git에 대해서 아무것도 모르던 제가 Push를 다해보네요..^^

### ISSUE THREAD

**Issue by rex-ya** [demun/FrontEndStudy#2]
4일정도 삽질해본결과 Git의 기본원리에 대해 대충 이해한듯합니다..ㅎㅎ

기념으로 Angular.js 예제보면서 동시에 삽질했던 정보도 공유해봅니다. (쬐끔밖에없지만;;)
너무 늦었을지도 모르겠군요..^^;

아무튼 우리 모두 화이팅입니다!
앵귤러팀 화이팅!!

**Comment by demun** [comment]
이것도 오픈인가요???ㅎㅎㅎㅎ
여하튼 축하합니다. git 의 세계에 온걸 환영합니다.
